### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by nichoth** [socketsupply/tapzero#7]
this is running on a Mac with M1

clone the repo, then do `npm i` and `npm test`

```
> tapzero@0.6.1 test
> npm run tsc && npm run lint && node test/harness.js && node test/index.js && npr type-coverage


> tapzero@0.6.1 tsc
> npr tsc -p jsconfig.json --maxNodeModuleJsDepth 0


> tapzero@0.6.1 lint
> npr tsdocstandard -v

TAP version 13
# a test
ok 1 null
ok 2 should be equal
ok 3 should be equal
# no options
ok 4 null
ok 5 should be equal
ok 6 should be equal
# async await
ok 7 should be equal
ok 8 should be equal
# async await no end
ok 9 should be equal
ok 10 should be equal
# async await promise
ok 11 should be equal
ok 12 should be equal
# async await promise without end
ok 13 should be equal
ok 14 should be equal

1..14
# tests 14
# pass  14

# ok
TAP version 13
# zerotap outputs TAP
ok 1 should be equivalent
# zerotap with two blocks
ok 2 should be equivalent
# zerotap handles failures
ok 3 should be equal
# zerotap handles errors
not ok 4 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# zero\nnot ok 1 Error: foo\n  ---\n    operator: ifError\n    expected: "no error"\n    actual:   "foo"\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: foo\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (internal/timers.js:$LINE:$COL)\n          at processTimers (internal/timers.js:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    actual: |-
      'TAP version 13\n# zero\nnot ok 1 Error: foo\n  ---\n    operator: ifError\n    expected: "no error"\n    actual:   "foo"\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: foo\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (node:internal/timers:$LINE:$COL)\n          at processTimers (node:internal/timers:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    at: verify (/Users/nick/code/tapzero/test/unit/smoke.js:126:12)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at verify (/Users/nick/code/tapzero/test/unit/smoke.js:126:12)
          at TestRunner.report (/Users/nick/code/tapzero/test/util.js:37:7)
          at TestRunner.run (/Users/nick/code/tapzero/index.js:424:12)
  ...
# zerotap handles multiple asserts
not ok 5 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# test one\nok 1 should be truthy\nok 2 message\nnot ok 3 some message\n  ---\n    operator: ok\n    expected: "truthy value"\n    actual:   false\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: some message\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.ok ($TAPE/index.js:$LINE:$COL)\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (internal/timers.js:$LINE:$COL)\n          at processTimers (internal/timers.js:$LINE:$COL)\n  ...\n\n1..3\n# tests 3\n# pass  2\n# fail  1'
    actual: |-
      'TAP version 13\n# test one\nok 1 should be truthy\nok 2 message\nnot ok 3 some message\n  ---\n    operator: ok\n    expected: "truthy value"\n    actual:   false\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: some message\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.ok ($TAPE/index.js:$LINE:$COL)\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (node:internal/timers:$LINE:$COL)\n          at processTimers (node:internal/timers:$LINE:$COL)\n  ...\n\n1..3\n# tests 3\n# pass  2\n# fail  1'
    at: verify (/Users/nick/code/tapzero/test/unit/smoke.js:168:12)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at verify (/Users/nick/code/tapzero/test/unit/smoke.js:168:12)
          at TestRunner.report (/Users/nick/code/tapzero/test/util.js:37:7)
          at TestRunner.run (/Users/nick/code/tapzero/index.js:424:12)
  ...
# zerotap with multiple blocks
ok 6 should be equal
# zerotap other methods
ok 7 should be equal
# zerotap undefined is string
not ok 8 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# test one\nnot ok 1 should be equal\n  ---\n    operator: equal\n    expected: "foo"\n    actual:   undefined\n    at:       Test.fn ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: should be equal\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.equal ($TAPE/index.js:$LINE:$COL)\n          at Test.fn ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (internal/timers.js:$LINE:$COL)\n          at processTimers (internal/timers.js:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    actual: |-
      'TAP version 13\n# test one\nnot ok 1 should be equal\n  ---\n    operator: equal\n    expected: "foo"\n    actual:   undefined\n    at:       Test.fn ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: should be equal\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.equal ($TAPE/index.js:$LINE:$COL)\n          at Test.fn ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (node:internal/timers:$LINE:$COL)\n          at processTimers (node:internal/timers:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    at: verify (/Users/nick/code/tapzero/test/unit/smoke.js:287:12)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at verify (/Users/nick/code/tapzero/test/unit/smoke.js:287:12)
          at TestRunner.report (/Users/nick/code/tapzero/test/util.js:37:7)
          at TestRunner.run (/Users/nick/code/tapzero/index.js:424:12)
  ...
# zerotap fail
not ok 9 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# test one\nnot ok 1 my message\n  ---\n    operator: fail\n    expected: "fail not called"\n    actual:   "fail called"\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: my message\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.fail ($TAPE/index.js:$LINE:$COL)\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (internal/timers.js:$LINE:$COL)\n          at processTimers (internal/timers.js:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    actual: |-
      'TAP version 13\n# test one\nnot ok 1 my message\n  ---\n    operator: fail\n    expected: "fail not called"\n    actual:   "fail called"\n    at:       Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n    stack:    |-\n      Error: my message\n          at Test._assert ($TAPE/index.js:$LINE:$COL)\n          at Test.fail ($TAPE/index.js:$LINE:$COL)\n          at Test._ [as fn] ($TEST/unit/smoke.js:$LINE:$COL)\n          at Test.run ($TAPE/index.js:$LINE:$COL)\n          at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n          at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n          at listOnTimeout (node:internal/timers:$LINE:$COL)\n          at processTimers (node:internal/timers:$LINE:$COL)\n  ...\n\n1..1\n# tests 1\n# pass  0\n# fail  1'
    at: verify (/Users/nick/code/tapzero/test/unit/smoke.js:329:12)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at verify (/Users/nick/code/tapzero/test/unit/smoke.js:329:12)
          at TestRunner.report (/Users/nick/code/tapzero/test/util.js:37:7)
          at TestRunner.run (/Users/nick/code/tapzero/index.js:424:12)
  ...
# test zora/case: adding_test_cases_async_fail.js
ok 10 should be equal
not ok 11 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# tester sync\nok 1 assert1\n\n1..1\n# tests 1\n# pass  1\n\n# ok\n$TAPE/index.js:$LINE\n      throw new Error(\'Cannot add() a test case after tests completed.\')\n      ^\n\nError: Cannot add() a test case after tests completed.\n    at TestRunner.add ($TAPE/index.js:$LINE:$COL)\n    at test ($TAPE/index.js:$LINE:$COL)\n    at Timeout._onTimeout ($TEST/zora/fixtures/adding_test_cases_async_fail.js:$LINE:$COL)\n    at listOnTimeout (internal/timers.js:$LINE:$COL)\n    at processTimers (internal/timers.js:$LINE:$COL)\n'
    actual: |-
      'TAP version 13\n# tester sync\nok 1 assert1\n\n1..1\n# tests 1\n# pass  1\n\n# ok\n$TAPE/index.js:$LINE\n      throw new Error(\'Cannot add() a test case after tests completed.\')\n      ^\n\nError: Cannot add() a test case after tests completed.\n    at TestRunner.add ($TAPE/index.js:$LINE:$COL)\n    at test ($TAPE/index.js:$LINE:$COL)\n    at Timeout._onTimeout ($TEST/zora/fixtures/adding_test_cases_async_fail.js:$LINE:$COL)\n    at listOnTimeout (node:internal/timers:$LINE:$COL)\n    at processTimers (node:internal/timers:$LINE:$COL)\n'
    at: equalDiff (/Users/nick/code/tapzero/test/zora/test-cases.js:46:5)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at equalDiff (/Users/nick/code/tapzero/test/zora/test-cases.js:46:5)
          at /Users/nick/code/tapzero/test/zora/test-cases.js:34:7
  ...


--------------diff:--------------

-------raw actual-----
TAP version 13
# tester sync
ok 1 assert1

1..1
# tests 1
# pass  1

# ok
$TAPE/index.js:$LINE
      throw new Error('Cannot add() a test case after tests completed.')
      ^

Error: Cannot add() a test case after tests completed.
    at TestRunner.add ($TAPE/index.js:$LINE:$COL)
    at test ($TAPE/index.js:$LINE:$COL)
    at Timeout._onTimeout ($TEST/zora/fixtures/adding_test_cases_async_fail.js:$LINE:$COL)
    at listOnTimeout (node:internal/timers:$LINE:$COL)
    at processTimers (node:internal/timers:$LINE:$COL)

------------------------
# test zora/case: async.js
ok 12 should be equal
ok 13 should be equal
# test zora/case: bailout_fail.js
ok 14 should be equal
not ok 15 should be equal
  ---
    operator: equal
    expected: |-
      'TAP version 13\n# will not go to the end\nok 1 okay\n$TAPE/index.js:$LINE\n  function rethrow () { throw err }\n                        ^\n\nError: Oh no!\n    at Test._ [as fn] ($TEST/zora/fixtures/bailout_fail.js:$LINE:$COL)\n    at Test.run ($TAPE/index.js:$LINE:$COL)\n    at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n    at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n    at listOnTimeout (internal/timers.js:$LINE:$COL)\n    at processTimers (internal/timers.js:$LINE:$COL)\n'
    actual: |-
      'TAP version 13\n# will not go to the end\nok 1 okay\n$TAPE/index.js:$LINE\n  function rethrow () { throw err }\n                        ^\n\nError: Oh no!\n    at Test._ [as fn] ($TEST/zora/fixtures/bailout_fail.js:$LINE:$COL)\n    at Test.run ($TAPE/index.js:$LINE:$COL)\n    at TestRunner.run ($TAPE/index.js:$LINE:$COL)\n    at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)\n    at listOnTimeout (node:internal/timers:$LINE:$COL)\n    at processTimers (node:internal/timers:$LINE:$COL)\n'
    at: equalDiff (/Users/nick/code/tapzero/test/zora/test-cases.js:46:5)
    stack: |-
      Error: should be equal
          at Test.assert [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at Test.equal (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:385:10)
          at Test.bound [as equal] (/Users/nick/code/tapzero/node_modules/@pre-bundled/tape/lib/test.js:77:32)
          at equalDiff (/Users/nick/code/tapzero/test/zora/test-cases.js:46:5)
          at /Users/nick/code/tapzero/test/zora/test-cases.js:34:7
  ...


--------------diff:--------------

-------raw actual-----
TAP version 13
# will not go to the end
ok 1 okay
$TAPE/index.js:$LINE
  function rethrow () { throw err }
                        ^

Error: Oh no!
    at Test._ [as fn] ($TEST/zora/fixtures/bailout_fail.js:$LINE:$COL)
    at Test.run ($TAPE/index.js:$LINE:$COL)
    at TestRunner.run ($TAPE/index.js:$LINE:$COL)
    at Timeout._onTimeout ($TAPE/index.js:$LINE:$COL)
    at listOnTimeout (node:internal/timers:$LINE:$COL)
    at processTimers (node:internal/timers:$LINE:$COL)

------------------------

1..15
# tests 15
# pass  9
# fail  6
```

**Comment by Raynos** [comment]
Stack trace comparison is non deterministic, some versions of node contain `node:` and others do not.
